apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-deployment
  labels:
    app: library
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: library
  template:
    metadata:
      labels:
        app: library
    spec:
      containers:
        - name: postgres
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: pass
          ports:
            - containerPort: 3066
          volumeMounts:
            - mountPath: /library-storage
              name: library-storage
      volumes:
        - name: library-storage
          persistentVolumeClaim:
            claimName: library-claim
