apiVersion: v1
kind: Pod
metadata:
  labels:
    run: demo-pod
  name: demo-pod
spec:
  containers:
    - image: nginx
      name: demo-pod
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
