apiVersion: v1
kind: Pod
metadata:
  labels:
    run: demo-pod
  name: demo-pod
spec:
  containers:
    - name: postgres
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: pass
      volumeMounts:
        - mountPath: /demo
          name: demo-pod-volume
  volumes:
    - name: demo-pod-volume
      emptyDir:
        sizeLimit: 500Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
